export const elements = {
  //-----------------Switch Screens----------------//
  playGameBtn: document.getElementById("playGameBtn"),
  startPageContainer: document.getElementById("startPageContainer"),
  gameContainer: document.getElementById("gameContainer"),
  //-----------------------------------------------//
  //-----------------Show instructions-------------//
  instructionsBtn: document.getElementById("instructionsBtn"),
  instructionsModal: document.getElementById("instructionsModal"),
  instructionsExitBtn: document.getElementById("modalExitBtn"),
  //-----------------------------------------------//
  //-----------------Player Form-------------------//
  player1Name: document.getElementById("player1Name").value.trim(),
  player2Name: document.getElementById("player2Name").value.trim(),
  player2HumanCheck: document.getElementById("player2Human").checked,
  player2AICheck: document.getElementById("player2AI").checked,
  //-----------------------------------------------//
  //-----------------Misc--------------------------//
  btnDiv: document.getElementById("btns"),
  //-----------------------------------------------//
  //-----------------Game Screen-------------------//
  player1NameGameScreen: document.getElementById("player1NameGameScreen"),
  player2NameGameScreen: document.getElementById("player2NameGameScreen"),
  player1GridTarget: document.getElementById("playerBoard"),
  player2GridTarget: document.getElementById("secondBoard"),
  player1TurnText: document.getElementById("playerTurnText"),
  player2TurnText: document.getElementById("secondPlayerTurnText"),
  player1Hits: document.getElementById("player1Hits"),
  player1Misses: document.getElementById("player1Misses"),
  player2Hits: document.getElementById("player2Hits"),
  player2Misses: document.getElementById("player2Misses"),
  //-----------------------------------------------//
  //-----------------Grid Elements-------------------//
  grid00: document.getElementById("0,0"),
  grid01: document.getElementById("0,1"),
  grid02: document.getElementById("0,2"),
  grid03: document.getElementById("0,3"),
  grid04: document.getElementById("0,4"),
  grid05: document.getElementById("0,5"),
  grid06: document.getElementById("0,6"),
  grid07: document.getElementById("0,7"),
  grid08: document.getElementById("0,8"),
  grid09: document.getElementById("0,9"),

  grid10: document.getElementById("1,0"),
  grid11: document.getElementById("1,1"),
  grid12: document.getElementById("1,2"),
  grid13: document.getElementById("1,3"),
  grid14: document.getElementById("1,4"),
  grid15: document.getElementById("1,5"),
  grid16: document.getElementById("1,6"),
  grid17: document.getElementById("1,7"),
  grid18: document.getElementById("1,8"),
  grid19: document.getElementById("1,9"),

  grid20: document.getElementById("2,0"),
  grid21: document.getElementById("2,1"),
  grid22: document.getElementById("2,2"),
  grid23: document.getElementById("2,3"),
  grid24: document.getElementById("2,4"),
  grid25: document.getElementById("2,5"),
  grid26: document.getElementById("2,6"),
  grid27: document.getElementById("2,7"),
  grid28: document.getElementById("2,8"),
  grid29: document.getElementById("2,9"),

  grid30: document.getElementById("3,0"),
  grid31: document.getElementById("3,1"),
  grid32: document.getElementById("3,2"),
  grid33: document.getElementById("3,3"),
  grid34: document.getElementById("3,4"),
  grid35: document.getElementById("3,5"),
  grid36: document.getElementById("3,6"),
  grid37: document.getElementById("3,7"),
  grid38: document.getElementById("3,8"),
  grid39: document.getElementById("3,9"),

  grid40: document.getElementById("4,0"),
  grid41: document.getElementById("4,1"),
  grid42: document.getElementById("4,2"),
  grid43: document.getElementById("4,3"),
  grid44: document.getElementById("4,4"),
  grid45: document.getElementById("4,5"),
  grid46: document.getElementById("4,6"),
  grid47: document.getElementById("4,7"),
  grid48: document.getElementById("4,8"),
  grid49: document.getElementById("4,9"),

  grid50: document.getElementById("5,0"),
  grid51: document.getElementById("5,1"),
  grid52: document.getElementById("5,2"),
  grid53: document.getElementById("5,3"),
  grid54: document.getElementById("5,4"),
  grid55: document.getElementById("5,5"),
  grid56: document.getElementById("5,6"),
  grid57: document.getElementById("5,7"),
  grid58: document.getElementById("5,8"),
  grid59: document.getElementById("5,9"),

  grid60: document.getElementById("6,0"),
  grid61: document.getElementById("6,1"),
  grid62: document.getElementById("6,2"),
  grid63: document.getElementById("6,3"),
  grid64: document.getElementById("6,4"),
  grid65: document.getElementById("6,5"),
  grid66: document.getElementById("6,6"),
  grid67: document.getElementById("6,7"),
  grid68: document.getElementById("6,8"),
  grid69: document.getElementById("6,9"),

  grid70: document.getElementById("7,0"),
  grid71: document.getElementById("7,1"),
  grid72: document.getElementById("7,2"),
  grid73: document.getElementById("7,3"),
  grid74: document.getElementById("7,4"),
  grid75: document.getElementById("7,5"),
  grid76: document.getElementById("7,6"),
  grid77: document.getElementById("7,7"),
  grid78: document.getElementById("7,8"),
  grid79: document.getElementById("7,9"),

  grid80: document.getElementById("8,0"),
  grid81: document.getElementById("8,1"),
  grid82: document.getElementById("8,2"),
  grid83: document.getElementById("8,3"),
  grid84: document.getElementById("8,4"),
  grid85: document.getElementById("8,5"),
  grid86: document.getElementById("8,6"),
  grid87: document.getElementById("8,7"),
  grid88: document.getElementById("8,8"),
  grid89: document.getElementById("8,9"),

  grid90: document.getElementById("9,0"),
  grid91: document.getElementById("9,1"),
  grid92: document.getElementById("9,2"),
  grid93: document.getElementById("9,3"),
  grid94: document.getElementById("9,4"),
  grid95: document.getElementById("9,5"),
  grid96: document.getElementById("9,6"),
  grid97: document.getElementById("9,7"),
  grid98: document.getElementById("9,8"),
  grid99: document.getElementById("9,9"),
};
